- platform: template
  sensors:
    # Sensor is On if the Guest network has any devices.
    wifi_guests:
      friendly_name: "Wifi Guest"
      value_template: >-
        {{ states('sensor.axeltech_guest')|int > 0 }}

    # Sensor if any HVAC unit is in defrost mode
    hvac_defrost:
      friendly_name: "HVAC Defrosting"
      device_class: "running"
      value_template: >-
        {{ is_state_attr('climate.den', 'defrost', true) or 
        is_state_attr('climate.living_room', 'defrost', true) or
        is_state_attr('climate.master_bedroom', 'defrost', true) or
        is_state_attr('climate.guest_room', 'defrost', true) }}

    # Sensor if any HVAC unit is in heat mode
    hvac_heat:
      friendly_name: "HVAC Heating"
      value_template: >-
        {{ is_state('climate.den', 'heat') or 
        is_state('climate.living_room', 'heat') or
        is_state('climate.master_bedroom', 'heat') or
        is_state('climate.guest_room', 'heat') }}
