# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# increase database commit interval to reduce wear on Pi SD card
recorder:
  commit_interval: 30

homeassistant:
  customize: !include customize.yaml

stream:

# Text to speech
tts:
  - platform: google_translate

# includes
automation: !include automations.yaml # automations maintained in HAAS UI
automation external: !include automations_external.yaml # file for entities created outside of UI

script: !include scripts.yaml

group: !include groups.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
template: !include template.yaml
