# virtual lights to support Alexa wake-up triggers
- platform: virtual
  name: "Wake Up Guest Room"
  support_brightness: true
  persistent: False
  initial_value: off
- platform: virtual
  name: "Wake Up Master Bedroom"
  support_brightness: true
  persistent: False
  initial_value: off
