# custom component to track number of devices on Unifi SSIDs
- platform: unifics
  name: wifi
  host: unifi.axeltech.com
  port: 443
  username: hass_sensor
  password: !secret unifi_hass_sensor
  verify_ssl: True
  udm: true

# number of days until home assistant cert expires
- platform: template
  sensors:
    s_cert_exiry_d:
      friendly_name: "Cert Expiry"
      value_template: >
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_home_axeltech_com')) - as_timestamp(now()) ) / 86400) | int }}
      unit_of_measurement: "days"

# Air Quality index
- platform: waqi
  token: !secret waqi_token
  locations:
    - "jersey city"
