# number of days until home assistant cert expires
- platform: template
  sensors:
    s_cert_exiry_d:
      friendly_name: "Cert Expiry"
      value_template: >
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_home_axeltech_com')) - as_timestamp(now()) ) / 86400) | int }}
      unit_of_measurement: "days"
    # airgradient sensors
    indoor_pm25_aqi:
      value_template: >-
        {% set pm02 = states('sensor.i_9psl_pm2_5') | float %}
        {% if pm02 <= 12.0 %}
          {{ ((50 - 0) / (12.0 - 0) * (pm02 - 0) + 0) | int }}
        {% elif pm02 <= 35.4 %}
          {{ ((100 - 50) / (35.4 - 12.0) * (pm02 - 12.0) + 50) | int }}
        {% elif pm02 <= 55.4 %}
          {{ ((150 - 100) / (55.4 - 35.4) * (pm02 - 35.4) + 100) | int }}
        {% elif pm02 <= 150.4 %}
          {{ ((200 - 150) / (150.4 - 55.4) * (pm02 - 55.4) + 150) | int }}
        {% elif pm02 <= 250.4 %}
          {{ ((300 - 200) / (250.4 - 150.4) * (pm02 - 150.4) + 200) | int }}
        {% elif pm02 <= 350.4 %}
          {{ ((400 - 300) / (350.4 - 250.4) * (pm02 - 250.4) + 300) | int }}
        {% elif pm02 <= 500.4 %}
          {{ ((500 - 400) / (500.4 - 350.4) * (pm02 - 350.4) + 400) | int }}
        {% else %}
          500
        {% endif %}
      unit_of_measurement: "AQI"
    outdoor_pm25_aqi:
      value_template: >-
        {% set pm02 = states('sensor.o_1pst_pm2_5') | float %}
        {% if pm02 <= 12.0 %}
          {{ ((50 - 0) / (12.0 - 0) * (pm02 - 0) + 0) | int }}
        {% elif pm02 <= 35.4 %}
          {{ ((100 - 50) / (35.4 - 12.0) * (pm02 - 12.0) + 50) | int }}
        {% elif pm02 <= 55.4 %}
          {{ ((150 - 100) / (55.4 - 35.4) * (pm02 - 35.4) + 100) | int }}
        {% elif pm02 <= 150.4 %}
          {{ ((200 - 150) / (150.4 - 55.4) * (pm02 - 55.4) + 150) | int }}
        {% elif pm02 <= 250.4 %}
          {{ ((300 - 200) / (250.4 - 150.4) * (pm02 - 150.4) + 200) | int }}
        {% elif pm02 <= 350.4 %}
          {{ ((400 - 300) / (350.4 - 250.4) * (pm02 - 250.4) + 300) | int }}
        {% elif pm02 <= 500.4 %}
          {{ ((500 - 400) / (500.4 - 350.4) * (pm02 - 350.4) + 400) | int }}
        {% else %}
          500
        {% endif %}
      unit_of_measurement: "AQI"
