# number of days until home assistant cert expires
- platform: template
  sensors:
    s_cert_exiry_d:
      friendly_name: "Cert Expiry"
      value_template: >
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_home_axeltech_com')) - as_timestamp(now()) ) / 86400) | int }}
      unit_of_measurement: "days"