# Rest API for Hue Motion Sensor
- platform: rest
  resource: !secret hue_living_room_motion
  name: 'Living Room Motion Sensor'
  method: put
  body_on: '{"config": {"on":true}}'
  body_off: '{"config": {"on":false}}'
  is_on_template: '{{ value_json.config.on == true }}'
  headers:
    Content-Type: application/json
- platform: rest
  resource: !secret hue_den_motion
  name: 'Den Motion Sensor'
  method: put
  body_on: '{"config": {"on":true}}'
  body_off: '{"config": {"on":false}}'
  is_on_template: '{{ value_json.config.on == true }}'
  headers:
    Content-Type: application/json
- platform: rest
  resource: !secret hue_laundry_room_motion
  name: 'Laundry Room Motion Sensor'
  method: put
  body_on: '{"config": {"on":true}}'
  body_off: '{"config": {"on":false}}'
  is_on_template: '{{ value_json.config.on == true }}'
  headers:
    Content-Type: application/json
- platform: rest
  resource: !secret hue_master_bedroom_motion
  name: 'Master Bedroom Motion Sensor'
  method: put
  body_on: '{"config": {"on":true}}'
  body_off: '{"config": {"on":false}}'
  is_on_template: '{{ value_json.config.on == true }}'
  headers:
    Content-Type: application/json
- platform: rest
  resource: !secret hue_guest_room_motion
  name: 'Guest Room Motion Sensor'
  method: put
  body_on: '{"config": {"on":true}}'
  body_off: '{"config": {"on":false}}'
  is_on_template: '{{ value_json.config.on == true }}'
  headers:
    Content-Type: application/json